### PR TITLE
Updating the code base to work with BagItTools

### PR DESCRIPTION
**Pull request by whikloj**
@mjordan Here is something you can play with and let me know how it is working for you. I didn't have a `createFile` function and discovered some bugs in my tag manifest creation so I pointed at my `develop` branch for now. Once you're happy I'll cut a `1.1.0` release and update the composer.json.

Just to explain a couple things

1. `Payload-Oxum` is generated by the library now so you can't add it and I don't currently have a way to turn it off. I probably also need to ensure I am doing it correctly. 
1. `Bagging-Date` is also added by the library so you can't add it and can't turn it off. Perhaps this is a feature you'd like?
1. I have one exception (`BagItException`) that I throw for everything. I could make more but it would be helpful to know where those divisions might be so I don't just go from 1 exception to 1,000 exceptions. 

In general `Bag` has a `Bag::create($directory)` function that creates the directory and the bag. The directory can't already exist. 

To load a bag you use `Bag::load($existing_file_or_directory)` it determines if it is an archive or not. If it is an archive file it opens it into a temporary directory for you to validate or work with.

### CODE REVIEW

**Comment by whikloj** [comment]
I went ahead and cut the minor release, needed to get the fixes in.

**Comment by mjordan** [comment]
@whikloj sorry about not testing sooner, will do so this evening.

**Comment by whikloj** [comment]
No worries, I hear you're some big shot librarian 😁

**Comment by mjordan** [comment]
@whikloj `composer install` ran without any issues. When I tried to generate a bag using 

`./bin/console app:islandora_bagger:create_bag --settings=sample_config.yml --node=1`

I got this:

```
In IslandoraBagger.php line 88:

  Attempted to load class "Bag" from namespace "whikloj\BagItTools".
  Did you forget a "use" statement for another namespace?
```

I noticed that the `vendor` directory didn't contain anything from whikloj:

`
autoload.php  bin  composer  doctrine  easycorp  guzzlehttp  league  monolog  nikic  pear  psr  ralouphie  scholarslab  squizlabs  symfony  twig
`

Also, I noticed that composer.lock didn't contain 'whikloj' either. So I deleted composer.lock, reran `composer install`, and now generating a bag works. 👍

**Comment by whikloj** [comment]
Sorry, I should have noted that I didn't update your composer.lock or symfony.lock files. I want sure what the lowest PHP version you were supporting was. If you let me know I'll update and add those files to the PR.

**Comment by mjordan** [comment]
I'd say 7.2 is reasonable. We'll need to warn users (the only one I know of is UPEI) about this and about changes in the plugin method signatures. I can do that via slack, I don't think we need to do a whole deprecation process thing.

**Comment by whikloj** [comment]
You could add a tag to your master branch for `1.0.0` and after you change add a `2.0.0`. Then they could still use the old code until they are ready to switch. I'll update the PR with a PHP 7.2 composer.lock file.

**Comment by mjordan** [comment]
Thanks for the suggestion, I'll do that.

**Pull request merged**
